# Generated by Django 5.2.17 on 2026-09-05 18:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(choices=[('Pre-Nursery', 'Pre-Nursery'), ('Nursery 1', 'Nursery 1'), ('Nursery 2', 'Nursery 2'), ('Nursery 3', 'Nursery 3'), ('Basic 1', 'Basic 1'), ('Basic 2', 'Basic 2'), ('Basic 3', 'Basic 3'), ('Basic 4', 'Basic 4'), ('Basic 5', 'Basic 5')], max_length=20)),
                ('term', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], max_length=10)),
                ('session', models.CharField(max_length=20)),
                ('zip_file', models.FileField(upload_to='results/compiled/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('reg_no', models.CharField(max_length=50, unique=True)),
                ('class_level', models.CharField(choices=[('Pre-Nursery', 'Pre-Nursery'), ('Nursery 1', 'Nursery 1'), ('Nursery 2', 'Nursery 2'), ('Nursery 3', 'Nursery 3'), ('Basic 1', 'Basic 1'), ('Basic 2', 'Basic 2'), ('Basic 3', 'Basic 3'), ('Basic 4', 'Basic 4'), ('Basic 5', 'Basic 5')], max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('level', models.CharField(blank=True, max_length=30)),
                ('term', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], max_length=10)),
                ('session', models.CharField(help_text='Example: 2026/2027', max_length=20)),
                ('term_ending', models.DateField()),
                ('next_term_begins', models.DateField()),
                ('total_score', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6)),
                ('position', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('class_size', models.PositiveIntegerField(default=0, editable=False)),
                ('overall_grade', models.CharField(blank=True, editable=False, max_length=1)),
                ('compiled_report', models.FileField(blank=True, editable=False, upload_to='results/individual/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('class_level', 'last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('section', models.CharField(choices=[('nursery', 'Nursery'), ('primary', 'Primary')], max_length=10)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ('section', 'display_order', 'name'),
                'constraints': [models.UniqueConstraint(fields=('name', 'section'), name='unique_subject_per_section')],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_ca', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('second_ca', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('exam', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('first_term', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('second_term', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('subject_average', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('grade', models.CharField(blank=True, editable=False, max_length=1)),
                ('remark', models.CharField(blank=True, editable=False, max_length=20)),
                ('subject_position', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('class_average', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='schoolresults.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='schoolresults.subject')),
            ],
            options={
                'ordering': ('subject__display_order', 'subject__name'),
                'constraints': [models.UniqueConstraint(fields=('student', 'subject'), name='unique_student_subject_result')],
            },
        ),
    ]
