# Generated by Django 5.2.17 on 2026-09-05 18:07

import schoolresults.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolresults', '0002_seed_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilation',
            name='zip_file',
            field=models.FileField(upload_to=schoolresults.models.compilation_upload_path),
        ),
    ]
