# Generated by Django 5.2.17 on 2026-09-05 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolresults', '0003_alter_compilation_zip_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CBTExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('class_level', models.CharField(choices=[('Pre-Nursery', 'Pre-Nursery'), ('Nursery 1', 'Nursery 1'), ('Nursery 2', 'Nursery 2'), ('Nursery 3', 'Nursery 3'), ('Basic 1', 'Basic 1'), ('Basic 2', 'Basic 2'), ('Basic 3', 'Basic 3'), ('Basic 4', 'Basic 4'), ('Basic 5', 'Basic 5')], max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(choices=[('Pre-Nursery', 'Pre-Nursery'), ('Nursery 1', 'Nursery 1'), ('Nursery 2', 'Nursery 2'), ('Nursery 3', 'Nursery 3'), ('Basic 1', 'Basic 1'), ('Basic 2', 'Basic 2'), ('Basic 3', 'Basic 3'), ('Basic 4', 'Basic 4'), ('Basic 5', 'Basic 5')], max_length=20)),
                ('can_enter_results', models.BooleanField(default=True)),
                ('can_take_attendance', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('incurred_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('receipt_no', models.CharField(blank=True, max_length=80)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfflineUpgradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_tier', models.CharField(choices=[('small', 'Small'), ('mid', 'Mid-Tier'), ('premium', 'Premium')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proof_details', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=30)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(choices=[('Pre-Nursery', 'Pre-Nursery'), ('Nursery 1', 'Nursery 1'), ('Nursery 2', 'Nursery 2'), ('Nursery 3', 'Nursery 3'), ('Basic 1', 'Basic 1'), ('Basic 2', 'Basic 2'), ('Basic 3', 'Basic 3'), ('Basic 4', 'Basic 4'), ('Basic 5', 'Basic 5')], max_length=20)),
                ('term', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], max_length=10)),
                ('session', models.CharField(max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('tier', models.CharField(choices=[('small', 'Small'), ('mid', 'Mid-Tier'), ('premium', 'Premium')], default='small', max_length=12)),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('trial', 'Trial')], default='trial', max_length=12)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('proprietor', 'Proprietor / Owner'), ('headmaster', 'Headmaster / Principal'), ('accountant', 'Accountant'), ('teacher', 'Teacher')], max_length=16)),
                ('custom_permissions', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('reference', models.CharField(max_length=150, unique=True)),
                ('target_tier', models.CharField(choices=[('small', 'Small'), ('mid', 'Mid-Tier'), ('premium', 'Premium')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Successful'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='result',
            name='unique_student_subject_result',
        ),
        migrations.RemoveConstraint(
            model_name='subject',
            name='unique_subject_per_section',
        ),
        migrations.AlterField(
            model_name='student',
            name='reg_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='schoolresults.student'),
        ),
        migrations.AddField(
            model_name='expense',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='schoolresults.student'),
        ),
        migrations.AddField(
            model_name='offlineupgraderequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upgrade_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offlineupgraderequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_upgrades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultlock',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_locks', to='schoolresults.school'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll', to='schoolresults.school'),
        ),
        migrations.AddField(
            model_name='offlineupgraderequest',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_upgrade_requests', to='schoolresults.school'),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='schoolresults.school'),
        ),
        migrations.AddField(
            model_name='expense',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='schoolresults.school'),
        ),
        migrations.AddField(
            model_name='classassignment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='schoolresults.school'),
        ),
        migrations.AddField(
            model_name='cbtexam',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_exams', to='schoolresults.school'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='schoolresults.school'),
        ),
        migrations.AddField(
            model_name='compilation',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compilations', to='schoolresults.school'),
        ),
        migrations.AddField(
            model_name='result',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='schoolresults.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schoolresults.school'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schoolresults.school'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.UniqueConstraint(fields=('school', 'student', 'subject'), name='unique_school_student_subject_result'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('school', 'reg_no'), name='unique_school_registration'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('school', 'name', 'section'), name='unique_school_subject_section'),
        ),
        migrations.AddField(
            model_name='schoolmembership',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='schoolresults.school'),
        ),
        migrations.AddField(
            model_name='schoolmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classassignment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='schoolresults.schoolmembership'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='schoolresults.school'),
        ),
        migrations.AddConstraint(
            model_name='resultlock',
            constraint=models.UniqueConstraint(fields=('school', 'class_level', 'term', 'session'), name='unique_result_lock'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('school', 'student', 'date'), name='unique_daily_attendance'),
        ),
        migrations.AddConstraint(
            model_name='schoolmembership',
            constraint=models.UniqueConstraint(fields=('school', 'user'), name='unique_school_membership'),
        ),
        migrations.AddConstraint(
            model_name='classassignment',
            constraint=models.UniqueConstraint(fields=('school', 'teacher', 'class_level'), name='unique_teacher_class'),
        ),
    ]
