<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration {public function up():void{
 Schema::create('admission_applications',function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->string('applicant_name');$t->string('guardian_name');$t->string('guardian_phone');$t->string('class_applied');$t->enum('status',['submitted','reviewing','accepted','rejected'])->default('submitted');$t->text('notes')->nullable();$t->timestamps();});
 Schema::create('library_books',function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->string('title');$t->string('author')->nullable();$t->string('isbn')->nullable();$t->unsignedInteger('copies')->default(1);$t->unsignedInteger('available_copies')->default(1);$t->timestamps();$t->unique(['school_id','isbn']);});
 Schema::create('book_loans',function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->foreignId('library_book_id')->constrained()->cascadeOnDelete();$t->foreignId('student_id')->constrained()->cascadeOnDelete();$t->date('borrowed_on');$t->date('due_on');$t->date('returned_on')->nullable();$t->timestamps();});
 Schema::create('inventory_items',function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('category');$t->integer('quantity')->default(0);$t->decimal('unit_cost',12,2)->default(0);$t->string('location')->nullable();$t->unsignedInteger('reorder_level')->default(0);$t->timestamps();});
 Schema::create('transport_routes',function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('vehicle_no')->nullable();$t->string('driver_name')->nullable();$t->string('driver_phone')->nullable();$t->decimal('term_fee',12,2)->default(0);$t->timestamps();});
 Schema::create('transport_students',function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->foreignId('transport_route_id')->constrained()->cascadeOnDelete();$t->foreignId('student_id')->constrained()->cascadeOnDelete();$t->string('pickup_point');$t->timestamps();$t->unique(['school_id','student_id']);});
 Schema::create('staff_leave_requests',function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->foreignId('staff_id')->constrained('users')->cascadeOnDelete();$t->date('starts_on');$t->date('ends_on');$t->string('type');$t->text('reason');$t->enum('status',['pending','approved','rejected'])->default('pending');$t->foreignId('reviewed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
 }public function down():void{foreach(['staff_leave_requests','transport_students','transport_routes','inventory_items','book_loans','library_books','admission_applications'] as $table)Schema::dropIfExists($table);}};
