<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration {public function up():void{
 Schema::create('guardians',function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('relationship');$t->string('phone');$t->string('email')->nullable();$t->string('address')->nullable();$t->timestamps();});
 Schema::create('guardian_student',function(Blueprint $t){$t->foreignId('guardian_id')->constrained()->cascadeOnDelete();$t->foreignId('student_id')->constrained()->cascadeOnDelete();$t->primary(['guardian_id','student_id']);});
 Schema::create('attendance_records',function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->foreignId('student_id')->constrained()->cascadeOnDelete();$t->date('date');$t->enum('status',['present','absent','late','excused']);$t->foreignId('recorded_by')->constrained('users')->restrictOnDelete();$t->string('note')->nullable();$t->timestamps();$t->unique(['school_id','student_id','date']);});
 Schema::create('fee_invoices',function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->foreignId('student_id')->constrained()->cascadeOnDelete();$t->string('session');$t->string('term');$t->string('description');$t->decimal('amount_due',12,2);$t->date('due_date')->nullable();$t->enum('status',['unpaid','partial','paid','waived'])->default('unpaid');$t->timestamps();});
 Schema::create('fee_payments',function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->foreignId('fee_invoice_id')->constrained()->cascadeOnDelete();$t->decimal('amount',12,2);$t->string('receipt_no')->unique();$t->enum('method',['cash','transfer','card','paystack','flutterwave']);$t->string('reference')->nullable();$t->timestamp('paid_at');$t->foreignId('received_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
 Schema::create('expenses',function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->string('category');$t->string('description');$t->decimal('amount',12,2);$t->date('incurred_on');$t->foreignId('recorded_by')->constrained('users')->restrictOnDelete();$t->timestamps();});
 Schema::create('payroll_records',function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->foreignId('staff_id')->constrained('users')->restrictOnDelete();$t->string('period');$t->decimal('gross_amount',12,2);$t->decimal('deductions',12,2)->default(0);$t->decimal('net_amount',12,2);$t->enum('status',['draft','approved','paid'])->default('draft');$t->timestamp('paid_at')->nullable();$t->timestamps();$t->unique(['school_id','staff_id','period']);});
 Schema::create('announcements',function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->string('title');$t->text('body');$t->enum('audience',['all','staff','students','parents','class']);$t->string('class_level')->nullable();$t->timestamp('published_at')->nullable();$t->foreignId('created_by')->constrained('users')->restrictOnDelete();$t->timestamps();});
 Schema::create('timetable_entries',function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->string('class_level');$t->foreignId('subject_id')->constrained()->cascadeOnDelete();$t->foreignId('teacher_id')->nullable()->constrained('users')->nullOnDelete();$t->unsignedTinyInteger('weekday');$t->time('starts_at');$t->time('ends_at');$t->string('room')->nullable();$t->timestamps();});
 }public function down():void{foreach(['timetable_entries','announcements','payroll_records','expenses','fee_payments','fee_invoices','attendance_records','guardian_student','guardians'] as $table)Schema::dropIfExists($table);}};
