<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration {public function up():void{
 Schema::table('schools',function(Blueprint $t){$t->boolean('block_results_for_debt')->default(true);$t->decimal('result_access_balance_limit',12,2)->default(0);$t->json('notification_channels')->nullable();});
 Schema::create('assessment_logs',function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->foreignId('student_id')->constrained()->cascadeOnDelete();$t->foreignId('subject_id')->nullable()->constrained()->nullOnDelete();$t->enum('type',['weekly_test','homework','project','behavior','discipline']);$t->string('title');$t->decimal('score',6,2)->nullable();$t->decimal('maximum_score',6,2)->nullable();$t->text('comment')->nullable();$t->foreignId('recorded_by')->constrained('users')->restrictOnDelete();$t->date('recorded_on');$t->timestamps();$t->index(['school_id','student_id','recorded_on']);});
 Schema::create('notification_logs',function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->foreignId('student_id')->nullable()->constrained()->nullOnDelete();$t->enum('channel',['sms','whatsapp','email','in_app']);$t->string('recipient');$t->string('template');$t->text('message');$t->enum('status',['queued','sent','failed'])->default('queued');$t->string('provider_reference')->nullable();$t->timestamp('sent_at')->nullable();$t->text('failure_reason')->nullable();$t->timestamps();});
 Schema::create('cbt_exams',function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->foreignId('subject_id')->constrained()->cascadeOnDelete();$t->string('title');$t->string('class_level');$t->unsignedInteger('duration_minutes');$t->decimal('pass_mark',5,2)->default(40);$t->boolean('shuffle_questions')->default(true);$t->boolean('published')->default(false);$t->timestamp('starts_at');$t->timestamp('ends_at');$t->timestamps();});
 Schema::create('cbt_questions',function(Blueprint $t){$t->id();$t->foreignId('cbt_exam_id')->constrained()->cascadeOnDelete();$t->text('question');$t->json('options');$t->string('correct_option');$t->decimal('mark',5,2)->default(1);$t->text('feedback')->nullable();$t->timestamps();});
 Schema::create('cbt_attempts',function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->foreignId('cbt_exam_id')->constrained()->cascadeOnDelete();$t->foreignId('student_id')->constrained()->cascadeOnDelete();$t->json('answers')->nullable();$t->decimal('score',7,2)->nullable();$t->timestamp('started_at');$t->timestamp('submitted_at')->nullable();$t->timestamps();$t->unique(['cbt_exam_id','student_id']);});
 Schema::create('audit_logs',function(Blueprint $t){$t->id();$t->foreignId('school_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('action');$t->string('entity_type');$t->unsignedBigInteger('entity_id')->nullable();$t->json('before')->nullable();$t->json('after')->nullable();$t->ipAddress('ip_address')->nullable();$t->string('user_agent',500)->nullable();$t->timestamps();$t->index(['school_id','entity_type','entity_id']);});
 }public function down():void{foreach(['audit_logs','cbt_attempts','cbt_questions','cbt_exams','notification_logs','assessment_logs'] as $table)Schema::dropIfExists($table);Schema::table('schools',fn(Blueprint $t)=>$t->dropColumn(['block_results_for_debt','result_access_balance_limit','notification_channels']));}};
